name: Feature Request
description: 'Report a feature request'
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-feature
    attributes:
      label: What feature do you want?
      description: Describe the feature you want.
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: textarea
    id: why-feature
    attributes:
      label: Why do you want this feature?
      description: Explain why you want this feature.
      placeholder: Tell us why you want this feature!
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Extra information
      description: Is there anything else we should know?
      placeholder: |
        - Other: [e.g. any other information]
    validations:
      required: false